name = "cloudflare-docker-proxy"
compatibility_date = "2024-11-06"
main = "src/index.ts"

routes = [
    { pattern = "docker.cmdcentral.net", custom_domain = true },
    # { pattern = "quay.libcuda.so", custom_domain = true },
    # { pattern = "gcr.libcuda.so", custom_domain = true },
    # { pattern = "k8s-gcr.libcuda.so", custom_domain = true },
    # { pattern = "k8s.libcuda.so", custom_domain = true },
    # { pattern = "ghcr.libcuda.so", custom_domain = true },
    # { pattern = "cloudsmith.libcuda.so", custom_domain = true },
]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
CUSTOM_DOMAIN = "docker.cmdcentral.net"
MODE = "production"
TARGET_UPSTREAM = "https://registry-1.docker.io"
