// Generated by Wrangler by running `wrangler types ./src/worker-configuration.d.ts --experimental-include-runtime`

interface Env {
	CUSTOM_DOMAIN: "docker.cmdcentral.net";
	MODE: "production";
	TARGET_UPSTREAM: "https://registry-1.docker.io";
}
